# 这是注释

# 存储你的 OpenAI API 密钥
OPENAI_API_KEY = "sk-zGzsKlEMKwMgpXPThLcEvOQ9fuDXG0J4oBqz-yepz1T3BlbkFJrGTEp7fUWyY0RU54RfRdLqhfyui7H_gWe76PDVX2UA" 

# 你也可以在这里存储其他敏感信息，例如数据库密码
DATABASE_PASSWORD = "your_database_password"
