name: Update Chat Logs

on:
  push:
    branches:
      - main

jobs:
  update_logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy chat logs to logs root
        run: |
          python -c "import shutil; shutil.copyfile('logs/史莱姆娘.pkl', 'logs/史莱姆娘.pkl')"
